# Generated by Django 4.0.1 on 2022-02-09 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sidhur2shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('product_image', models.FileField(default='settings.MEDIA_ROOT/media/random.jpg', upload_to='media')),
                ('tags', models.CharField(choices=[('Mob', 'Mobile'), ('Com', 'Computer'), ('Tv', 'Tv'), ('Con', 'Console'), ('Tab', 'Tablet')], default='Mob', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('address', models.TextField(default='')),
                ('instructions', models.CharField(max_length=200, null=True)),
                ('order_status', models.CharField(choices=[('FL', 'Failed'), ('PR', 'Processing'), ('CP', 'Completed')], default='PR', max_length=20)),
                ('payment_status', models.CharField(choices=[('SC', 'Stocked'), ('DP', 'Dispatched'), ('AR', 'Arrived'), ('SH', 'Shipped')], default='SC', max_length=20)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidhur2shop.cart')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('time', models.DateTimeField(auto_now=True)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidhur2shop.cart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidhur2shop.product')),
            ],
        ),
    ]
