# Generated by Django 4.0.1 on 2022-01-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidhur2shop', '0002_basket_product_order_basketitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='basketitems',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('FL', 'Failed'), ('PR', 'Processing'), ('CP', 'Completed')], default='PR', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('SC', 'Stocked'), ('DP', 'Dispatched'), ('AR', 'Arrived'), ('SH', 'Shipped')], default='SC', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(default='settings.MEDIA_ROOT/media/random.jpg', upload_to='media'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(choices=[('Mob', 'Mobile'), ('Com', 'Computer'), ('Tv', 'Tv'), ('Con', 'Console'), ('Tab', 'Tablet')], default='Mob', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
