# Generated by Django 4.0.1 on 2022-03-09 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidhur2shop', '0003_cartitems_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='name',
        ),
    ]
