# Generated by Django 4.0.1 on 2022-04-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidhur2shop', '0004_remove_cartitems_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(choices=[('Elect', 'Electronic'), ('Equip', 'Equipment'), ('Mach', 'Machine'), ('Work', 'Workout')], default='Equip', max_length=20),
        ),
    ]
